name: project_pokemon
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.1.0
  dio: ^4.0.0
  flutter_bloc: ^7.3.0
  flutter_svg: ^0.22.0
  palette_generator: ^0.3.1
  shared_preferences: ^2.0.7
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/favorite.png
    - assets/png/pokeball.png
    - assets/png/settings.png
    - assets/png/pokedex.png
    - assets/svg/pokemon_logo.svg

flutter_intl:
  enabled: true
  
